
all:
	@(cd src; $(MAKE))
	@(cd /home/ilian/git-projects/pyqtlibtest/PyMyLabel-master/modules; $(MAKE))

install:
	@(cd src; $(MAKE) install)
	@(cd /home/ilian/git-projects/pyqtlibtest/PyMyLabel-master/modules; $(MAKE) install)

clean:
	@(cd src; $(MAKE) clean)
	@(cd /home/ilian/git-projects/pyqtlibtest/PyMyLabel-master/modules; $(MAKE) clean)
