/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19
 */

#ifndef _PyMyLabelAPI_H
#define _PyMyLabelAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_7_1


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_mouseDoubleClickEvent 0
#define sipName_mouseDoubleClickEvent &sipStrings_PyMyLabel[0]
#define sipNameNr_focusPreviousChild 22
#define sipName_focusPreviousChild &sipStrings_PyMyLabel[22]
#define sipNameNr_focusNextPrevChild 41
#define sipName_focusNextPrevChild &sipStrings_PyMyLabel[41]
#define sipNameNr_destroySubWindows 60
#define sipName_destroySubWindows &sipStrings_PyMyLabel[60]
#define sipNameNr_hasHeightForWidth 78
#define sipName_hasHeightForWidth &sipStrings_PyMyLabel[78]
#define sipNameNr_mouseReleaseEvent 96
#define sipName_mouseReleaseEvent &sipStrings_PyMyLabel[96]
#define sipNameNr_isSignalConnected 114
#define sipName_isSignalConnected &sipStrings_PyMyLabel[114]
#define sipNameNr_senderSignalIndex 132
#define sipName_senderSignalIndex &sipStrings_PyMyLabel[132]
#define sipNameNr_destroyOldWindow 150
#define sipName_destroyOldWindow &sipStrings_PyMyLabel[150]
#define sipNameNr_initializeWindow 167
#define sipName_initializeWindow &sipStrings_PyMyLabel[167]
#define sipNameNr_updateMicroFocus 184
#define sipName_updateMicroFocus &sipStrings_PyMyLabel[184]
#define sipNameNr_contextMenuEvent 201
#define sipName_contextMenuEvent &sipStrings_PyMyLabel[201]
#define sipNameNr_inputMethodEvent 218
#define sipName_inputMethodEvent &sipStrings_PyMyLabel[218]
#define sipNameNr_inputMethodQuery 235
#define sipName_inputMethodQuery &sipStrings_PyMyLabel[235]
#define sipNameNr_disconnectNotify 252
#define sipName_disconnectNotify &sipStrings_PyMyLabel[252]
#define sipNameNr_initStyleOption 269
#define sipName_initStyleOption &sipStrings_PyMyLabel[269]
#define sipNameNr_minimumSizeHint 285
#define sipName_minimumSizeHint &sipStrings_PyMyLabel[285]
#define sipNameNr_mousePressEvent 301
#define sipName_mousePressEvent &sipStrings_PyMyLabel[301]
#define sipNameNr_keyReleaseEvent 317
#define sipName_keyReleaseEvent &sipStrings_PyMyLabel[317]
#define sipNameNr_deviceTransform 333
#define sipName_deviceTransform &sipStrings_PyMyLabel[333]
#define sipNameNr_internal_format 349
#define sipName_internal_format &sipStrings_PyMyLabel[349]
#define sipNameNr_aspectRatioMode 365
#define sipName_aspectRatioMode &sipStrings_PyMyLabel[365]
#define sipNameNr_focusNextChild 381
#define sipName_focusNextChild &sipStrings_PyMyLabel[381]
#define sipNameNr_heightForWidth 396
#define sipName_heightForWidth &sipStrings_PyMyLabel[396]
#define sipNameNr_dragLeaveEvent 411
#define sipName_dragLeaveEvent &sipStrings_PyMyLabel[411]
#define sipNameNr_dragEnterEvent 426
#define sipName_dragEnterEvent &sipStrings_PyMyLabel[426]
#define sipNameNr_mouseMoveEvent 441
#define sipName_mouseMoveEvent &sipStrings_PyMyLabel[441]
#define sipNameNr_changedSignal 456
#define sipName_changedSignal &sipStrings_PyMyLabel[456]
#define sipNameNr_sharedPainter 470
#define sipName_sharedPainter &sipStrings_PyMyLabel[470]
#define sipNameNr_destroyWindow 484
#define sipName_destroyWindow &sipStrings_PyMyLabel[484]
#define sipNameNr_thresholdTime 498
#define sipName_thresholdTime &sipStrings_PyMyLabel[498]
#define sipNameNr_dragMoveEvent 512
#define sipName_dragMoveEvent &sipStrings_PyMyLabel[512]
#define sipNameNr_keyPressEvent 526
#define sipName_keyPressEvent &sipStrings_PyMyLabel[526]
#define sipNameNr_focusOutEvent 540
#define sipName_focusOutEvent &sipStrings_PyMyLabel[540]
#define sipNameNr_transformMode 554
#define sipName_transformMode &sipStrings_PyMyLabel[554]
#define sipNameNr_connectNotify 255
#define sipName_connectNotify &sipStrings_PyMyLabel[255]
#define sipNameNr_sourceRegion 568
#define sipName_sourceRegion &sipStrings_PyMyLabel[568]
#define sipNameNr_targetOffset 581
#define sipName_targetOffset &sipStrings_PyMyLabel[581]
#define sipNameNr_midLineWidth 594
#define sipName_midLineWidth &sipStrings_PyMyLabel[594]
#define sipNameNr_focusInEvent 607
#define sipName_focusInEvent &sipStrings_PyMyLabel[607]
#define sipNameNr_boundingRect 620
#define sipName_boundingRect &sipStrings_PyMyLabel[620]
#define sipNameNr_initPainter 633
#define sipName_initPainter &sipStrings_PyMyLabel[633]
#define sipNameNr_nativeEvent 645
#define sipName_nativeEvent &sipStrings_PyMyLabel[645]
#define sipNameNr_actionEvent 657
#define sipName_actionEvent &sipStrings_PyMyLabel[657]
#define sipNameNr_changeEvent 669
#define sipName_changeEvent &sipStrings_PyMyLabel[669]
#define sipNameNr_tabletEvent 681
#define sipName_tabletEvent &sipStrings_PyMyLabel[681]
#define sipNameNr_matchPolicy 693
#define sipName_matchPolicy &sipStrings_PyMyLabel[693]
#define sipNameNr_resizeEvent 705
#define sipName_resizeEvent &sipStrings_PyMyLabel[705]
#define sipNameNr_paintEngine 717
#define sipName_paintEngine &sipStrings_PyMyLabel[717]
#define sipNameNr_customEvent 729
#define sipName_customEvent &sipStrings_PyMyLabel[729]
#define sipNameNr_eventFilter 741
#define sipName_eventFilter &sipStrings_PyMyLabel[741]
#define sipNameNr_enterEvent 753
#define sipName_enterEvent &sipStrings_PyMyLabel[753]
#define sipNameNr_leaveEvent 764
#define sipName_leaveEvent &sipStrings_PyMyLabel[764]
#define sipNameNr_constraint 775
#define sipName_constraint &sipStrings_PyMyLabel[775]
#define sipNameNr_closeEvent 786
#define sipName_closeEvent &sipStrings_PyMyLabel[786]
#define sipNameNr_repeatTime 797
#define sipName_repeatTime &sipStrings_PyMyLabel[797]
#define sipNameNr_wheelEvent 808
#define sipName_wheelEvent &sipStrings_PyMyLabel[808]
#define sipNameNr_columnSpan 819
#define sipName_columnSpan &sipStrings_PyMyLabel[819]
#define sipNameNr_paintEvent 830
#define sipName_paintEvent &sipStrings_PyMyLabel[830]
#define sipNameNr_genMipMaps 841
#define sipName_genMipMaps &sipStrings_PyMyLabel[841]
#define sipNameNr_setVisible 852
#define sipName_setVisible &sipStrings_PyMyLabel[852]
#define sipNameNr_childEvent 863
#define sipName_childEvent &sipStrings_PyMyLabel[863]
#define sipNameNr_timerEvent 874
#define sipName_timerEvent &sipStrings_PyMyLabel[874]
#define sipNameNr_drawFrame 885
#define sipName_drawFrame &sipStrings_PyMyLabel[885]
#define sipNameNr_dropEvent 895
#define sipName_dropEvent &sipStrings_PyMyLabel[895]
#define sipNameNr_hideEvent 905
#define sipName_hideEvent &sipStrings_PyMyLabel[905]
#define sipNameNr_showEvent 915
#define sipName_showEvent &sipStrings_PyMyLabel[915]
#define sipNameNr_moveEvent 925
#define sipName_moveEvent &sipStrings_PyMyLabel[925]
#define sipNameNr_operation 935
#define sipName_operation &sipStrings_PyMyLabel[935]
#define sipNameNr_lineWidth 945
#define sipName_lineWidth &sipStrings_PyMyLabel[945]
#define sipNameNr_directory 955
#define sipName_directory &sipStrings_PyMyLabel[955]
#define sipNameNr_alignment 965
#define sipName_alignment &sipStrings_PyMyLabel[965]
#define sipNameNr_receivers 975
#define sipName_receivers &sipStrings_PyMyLabel[975]
#define sipNameNr_precision 985
#define sipName_precision &sipStrings_PyMyLabel[985]
#define sipNameNr_PyMyLabel 995
#define sipName_PyMyLabel &sipStrings_PyMyLabel[995]
#define sipNameNr_shortcut 1005
#define sipName_shortcut &sipStrings_PyMyLabel[1005]
#define sipNameNr_userData 1014
#define sipName_userData &sipStrings_PyMyLabel[1014]
#define sipNameNr_sizeHint 1023
#define sipName_sizeHint &sipStrings_PyMyLabel[1023]
#define sipNameNr_fillRule 1032
#define sipName_fillRule &sipStrings_PyMyLabel[1032]
#define sipNameNr_tabArray 1041
#define sipName_tabArray &sipStrings_PyMyLabel[1041]
#define sipNameNr_tabStops 1050
#define sipName_tabStops &sipStrings_PyMyLabel[1050]
#define sipNameNr_nameType 1059
#define sipName_nameType &sipStrings_PyMyLabel[1059]
#define sipNameNr_position 1068
#define sipName_position &sipStrings_PyMyLabel[1068]
#define sipNameNr_property 1077
#define sipName_property &sipStrings_PyMyLabel[1077]
#define sipNameNr_MyLabel 997
#define sipName_MyLabel &sipStrings_PyMyLabel[997]
#define sipNameNr_yMargin 1086
#define sipName_yMargin &sipStrings_PyMyLabel[1086]
#define sipNameNr_xMargin 1094
#define sipName_xMargin &sipStrings_PyMyLabel[1094]
#define sipNameNr_rowSpan 1102
#define sipName_rowSpan &sipStrings_PyMyLabel[1102]
#define sipNameNr_exposed 1110
#define sipName_exposed &sipStrings_PyMyLabel[1110]
#define sipNameNr_buffers 1118
#define sipName_buffers &sipStrings_PyMyLabel[1118]
#define sipNameNr_sources 1126
#define sipName_sources &sipStrings_PyMyLabel[1126]
#define sipNameNr_destroy 1134
#define sipName_destroy &sipStrings_PyMyLabel[1134]
#define sipNameNr_quality 1142
#define sipName_quality &sipStrings_PyMyLabel[1142]
#define sipNameNr_devType 1150
#define sipName_devType &sipStrings_PyMyLabel[1150]
#define sipNameNr_filters 1158
#define sipName_filters &sipStrings_PyMyLabel[1158]
#define sipNameNr_enabled 1166
#define sipName_enabled &sipStrings_PyMyLabel[1166]
#define sipNameNr_options 1174
#define sipName_options &sipStrings_PyMyLabel[1174]
#define sipNameNr_sunken 1182
#define sipName_sunken &sipStrings_PyMyLabel[1182]
#define sipNameNr_layers 1189
#define sipName_layers &sipStrings_PyMyLabel[1189]
#define sipNameNr_stride 1196
#define sipName_stride &sipStrings_PyMyLabel[1196]
#define sipNameNr_metric 1203
#define sipName_metric &sipStrings_PyMyLabel[1203]
#define sipNameNr_window 1210
#define sipName_window &sipStrings_PyMyLabel[1210]
#define sipNameNr_create 1217
#define sipName_create &sipStrings_PyMyLabel[1217]
#define sipNameNr_proper 1224
#define sipName_proper &sipStrings_PyMyLabel[1224]
#define sipNameNr_sender 1231
#define sipName_sender &sipStrings_PyMyLabel[1231]
#define sipNameNr_value9 1238
#define sipName_value9 &sipStrings_PyMyLabel[1238]
#define sipNameNr_value8 1245
#define sipName_value8 &sipStrings_PyMyLabel[1245]
#define sipNameNr_value7 1252
#define sipName_value7 &sipStrings_PyMyLabel[1252]
#define sipNameNr_value6 1259
#define sipName_value6 &sipStrings_PyMyLabel[1259]
#define sipNameNr_value5 1266
#define sipName_value5 &sipStrings_PyMyLabel[1266]
#define sipNameNr_value4 1273
#define sipName_value4 &sipStrings_PyMyLabel[1273]
#define sipNameNr_value3 1280
#define sipName_value3 &sipStrings_PyMyLabel[1280]
#define sipNameNr_value2 1287
#define sipName_value2 &sipStrings_PyMyLabel[1287]
#define sipNameNr_value1 1294
#define sipName_value1 &sipStrings_PyMyLabel[1294]
#define sipNameNr_value0 1301
#define sipName_value0 &sipStrings_PyMyLabel[1301]
#define sipNameNr_system 1308
#define sipName_system &sipStrings_PyMyLabel[1308]
#define sipNameNr_symbol 1315
#define sipName_symbol &sipStrings_PyMyLabel[1315]
#define sipNameNr_suffix 1322
#define sipName_suffix &sipStrings_PyMyLabel[1322]
#define sipNameNr_offset 1329
#define sipName_offset &sipStrings_PyMyLabel[1329]
#define sipNameNr_prefix 1336
#define sipName_prefix &sipStrings_PyMyLabel[1336]
#define sipNameNr_filter 1343
#define sipName_filter &sipStrings_PyMyLabel[1343]
#define sipNameNr_option 1350
#define sipName_option &sipStrings_PyMyLabel[1350]
#define sipNameNr_locale 1357
#define sipName_locale &sipStrings_PyMyLabel[1357]
#define sipNameNr_format 358
#define sipName_format &sipStrings_PyMyLabel[358]
#define sipNameNr_column 1364
#define sipName_column &sipStrings_PyMyLabel[1364]
#define sipNameNr_object 1371
#define sipName_object &sipStrings_PyMyLabel[1371]
#define sipNameNr_parent 1378
#define sipName_parent &sipStrings_PyMyLabel[1378]
#define sipNameNr_brush 1385
#define sipName_brush &sipStrings_PyMyLabel[1385]
#define sipNameNr_types 1391
#define sipName_types &sipStrings_PyMyLabel[1391]
#define sipNameNr_order 1397
#define sipName_order &sipStrings_PyMyLabel[1397]
#define sipNameNr_roles 1403
#define sipName_roles &sipStrings_PyMyLabel[1403]
#define sipNameNr_flags 1409
#define sipName_flags &sipStrings_PyMyLabel[1409]
#define sipNameNr_event 1415
#define sipName_event &sipStrings_PyMyLabel[1415]
#define sipNameNr_msecs 1421
#define sipName_msecs &sipStrings_PyMyLabel[1421]
#define sipNameNr_state 1427
#define sipName_state &sipStrings_PyMyLabel[1427]
#define sipNameNr_mode 1433
#define sipName_mode &sipStrings_PyMyLabel[1433]
#define sipNameNr_name 1438
#define sipName_name &sipStrings_PyMyLabel[1438]
#define sipNameNr_base 1443
#define sipName_base &sipStrings_PyMyLabel[1443]
#define sipNameNr_fill 1448
#define sipName_fill &sipStrings_PyMyLabel[1448]
#define sipNameNr_from 1453
#define sipName_from &sipStrings_PyMyLabel[1453]
#define sipNameNr_sort 1458
#define sipName_sort &sipStrings_PyMyLabel[1458]
#define sipNameNr_pen 1463
#define sipName_pen &sipStrings_PyMyLabel[1463]
#define sipNameNr_pos 1467
#define sipName_pos &sipStrings_PyMyLabel[1467]
#define sipNameNr_sw 1471
#define sipName_sw &sipStrings_PyMyLabel[1471]
#define sipNameNr_sh 1388
#define sipName_sh &sipStrings_PyMyLabel[1388]
#define sipNameNr_sy 1474
#define sipName_sy &sipStrings_PyMyLabel[1474]
#define sipNameNr_sx 1477
#define sipName_sx &sipStrings_PyMyLabel[1477]
#define sipNameNr_at 362
#define sipName_at &sipStrings_PyMyLabel[362]

#define sipMalloc                   sipAPI_PyMyLabel->api_malloc
#define sipFree                     sipAPI_PyMyLabel->api_free
#define sipBuildResult              sipAPI_PyMyLabel->api_build_result
#define sipCallMethod               sipAPI_PyMyLabel->api_call_method
#define sipCallProcedureMethod      sipAPI_PyMyLabel->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_PyMyLabel->api_call_error_handler
#define sipParseResultEx            sipAPI_PyMyLabel->api_parse_result_ex
#define sipParseResult              sipAPI_PyMyLabel->api_parse_result
#define sipParseArgs                sipAPI_PyMyLabel->api_parse_args
#define sipParseKwdArgs             sipAPI_PyMyLabel->api_parse_kwd_args
#define sipParsePair                sipAPI_PyMyLabel->api_parse_pair
#define sipCommonDtor               sipAPI_PyMyLabel->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_PyMyLabel->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_PyMyLabel->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_PyMyLabel->api_convert_to_void_ptr
#define sipAddException             sipAPI_PyMyLabel->api_add_exception
#define sipNoFunction               sipAPI_PyMyLabel->api_no_function
#define sipNoMethod                 sipAPI_PyMyLabel->api_no_method
#define sipAbstractMethod           sipAPI_PyMyLabel->api_abstract_method
#define sipBadClass                 sipAPI_PyMyLabel->api_bad_class
#define sipBadCatcherResult         sipAPI_PyMyLabel->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_PyMyLabel->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_PyMyLabel->api_bad_operator_arg
#define sipTrace                    sipAPI_PyMyLabel->api_trace
#define sipTransferBack             sipAPI_PyMyLabel->api_transfer_back
#define sipTransferTo               sipAPI_PyMyLabel->api_transfer_to
#define sipTransferBreak            sipAPI_PyMyLabel->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_PyMyLabel->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_PyMyLabel->api_wrapper_type
#define sipWrapperType_Type         sipAPI_PyMyLabel->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_PyMyLabel->api_voidptr_type
#define sipGetPyObject              sipAPI_PyMyLabel->api_get_pyobject
#define sipGetAddress               sipAPI_PyMyLabel->api_get_address
#define sipGetMixinAddress          sipAPI_PyMyLabel->api_get_mixin_address
#define sipGetCppPtr                sipAPI_PyMyLabel->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_PyMyLabel->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_PyMyLabel->api_is_py_method
#define sipCallHook                 sipAPI_PyMyLabel->api_call_hook
#define sipEndThread                sipAPI_PyMyLabel->api_end_thread
#define sipConnectRx                sipAPI_PyMyLabel->api_connect_rx
#define sipDisconnectRx             sipAPI_PyMyLabel->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_PyMyLabel->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_PyMyLabel->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_PyMyLabel->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_PyMyLabel->api_add_type_instance
#define sipFreeSipslot              sipAPI_PyMyLabel->api_free_sipslot
#define sipSameSlot                 sipAPI_PyMyLabel->api_same_slot
#define sipPySlotExtend             sipAPI_PyMyLabel->api_pyslot_extend
#define sipConvertRx                sipAPI_PyMyLabel->api_convert_rx
#define sipAddDelayedDtor           sipAPI_PyMyLabel->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_PyMyLabel->api_can_convert_to_type
#define sipConvertToType            sipAPI_PyMyLabel->api_convert_to_type
#define sipForceConvertToType       sipAPI_PyMyLabel->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_PyMyLabel->api_can_convert_to_enum
#define sipReleaseType              sipAPI_PyMyLabel->api_release_type
#define sipConvertFromType          sipAPI_PyMyLabel->api_convert_from_type
#define sipConvertFromNewType       sipAPI_PyMyLabel->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_PyMyLabel->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_PyMyLabel->api_convert_from_enum
#define sipGetState                 sipAPI_PyMyLabel->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_PyMyLabel->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_PyMyLabel->api_export_symbol
#define sipImportSymbol             sipAPI_PyMyLabel->api_import_symbol
#define sipFindType                 sipAPI_PyMyLabel->api_find_type
#define sipFindNamedEnum            sipAPI_PyMyLabel->api_find_named_enum
#define sipBytes_AsChar             sipAPI_PyMyLabel->api_bytes_as_char
#define sipBytes_AsString           sipAPI_PyMyLabel->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_PyMyLabel->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_PyMyLabel->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_PyMyLabel->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_PyMyLabel->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_PyMyLabel->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_PyMyLabel->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_PyMyLabel->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_PyMyLabel->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_PyMyLabel->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_PyMyLabel->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_PyMyLabel->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_PyMyLabel->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_PyMyLabel->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_PyMyLabel->api_save_slot
#define sipClearAnySlotReference    sipAPI_PyMyLabel->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_PyMyLabel->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_PyMyLabel->api_deprecated
#define sipGetReference             sipAPI_PyMyLabel->api_get_reference
#define sipKeepReference            sipAPI_PyMyLabel->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_PyMyLabel->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_PyMyLabel->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_PyMyLabel->api_type_from_py_type_object
#define sipTypeScope                sipAPI_PyMyLabel->api_type_scope
#define sipResolveTypedef           sipAPI_PyMyLabel->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_PyMyLabel->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_PyMyLabel->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_PyMyLabel->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_PyMyLabel->api_enable_autoconversion
#define sipInitMixin                sipAPI_PyMyLabel->api_init_mixin
#define sipExportModule             sipAPI_PyMyLabel->api_export_module
#define sipInitModule               sipAPI_PyMyLabel->api_init_module
#define sipGetInterpreter           sipAPI_PyMyLabel->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_PyMyLabel->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_PyMyLabel->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_PyMyLabel->api_get_type_user_data
#define sipPyTypeDict               sipAPI_PyMyLabel->api_py_type_dict
#define sipPyTypeName               sipAPI_PyMyLabel->api_py_type_name
#define sipGetCFunction             sipAPI_PyMyLabel->api_get_c_function
#define sipGetMethod                sipAPI_PyMyLabel->api_get_method
#define sipFromMethod               sipAPI_PyMyLabel->api_from_method
#define sipGetDate                  sipAPI_PyMyLabel->api_get_date
#define sipFromDate                 sipAPI_PyMyLabel->api_from_date
#define sipGetDateTime              sipAPI_PyMyLabel->api_get_datetime
#define sipFromDateTime             sipAPI_PyMyLabel->api_from_datetime
#define sipGetTime                  sipAPI_PyMyLabel->api_get_time
#define sipFromTime                 sipAPI_PyMyLabel->api_from_time
#define sipIsUserType               sipAPI_PyMyLabel->api_is_user_type
#define sipGetFrame                 sipAPI_PyMyLabel->api_get_frame
#define sipCheckPluginForType       sipAPI_PyMyLabel->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_PyMyLabel->api_unicode_new
#define sipUnicodeWrite             sipAPI_PyMyLabel->api_unicode_write
#define sipUnicodeData              sipAPI_PyMyLabel->api_unicode_data
#define sipGetBufferInfo            sipAPI_PyMyLabel->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_PyMyLabel->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_PyMyLabel->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_PyMyLabel->api_is_derived_class
#define sipGetUserObject            sipAPI_PyMyLabel->api_get_user_object
#define sipSetUserObject            sipAPI_PyMyLabel->api_set_user_object

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_PyMyLabel->api_map_string_to_class
#define sipMapIntToClass            sipAPI_PyMyLabel->api_map_int_to_class
#define sipFindClass                sipAPI_PyMyLabel->api_find_class
#define sipFindMappedType           sipAPI_PyMyLabel->api_find_mapped_type
#define sipConvertToArray           sipAPI_PyMyLabel->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_PyMyLabel->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_PyMyLabel->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_PyMyLabel[];

#define sipType_MyLabel sipExportedTypes_PyMyLabel[0]
#define sipClass_MyLabel sipExportedTypes_PyMyLabel[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyMyLabel_MyLabel;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_PyMyLabel;
extern sipExportedModuleDef sipModuleAPI_PyMyLabel;
extern sipTypeDef *sipExportedTypes_PyMyLabel[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_PyMyLabel_QtCore[8].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_PyMyLabel_QtCore[8].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_PyMyLabel_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_PyMyLabel_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_PyMyLabel_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_PyMyLabel_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_PyMyLabel_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_PyMyLabel_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_PyMyLabel_QtCore[6].it_td
#define sipClass_QTimerEvent sipImportedTypes_PyMyLabel_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_PyMyLabel_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_PyMyLabel_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_PyMyLabel_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_PyMyLabel_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_PyMyLabel_QtCore[5].it_td
#define sipClass_QSize sipImportedTypes_PyMyLabel_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_PyMyLabel_QtCore[7].it_td
#define sipClass_QVariant sipImportedTypes_PyMyLabel_QtCore[7].it_td->u.td_wrapper_type

#define sipType_quintptr sipImportedTypes_PyMyLabel_QtCore[9].it_td
extern sipImportedTypeDef sipImportedTypes_PyMyLabel_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_PyMyLabel_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_PyMyLabel_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_PyMyLabel_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_PyMyLabel_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_PyMyLabel_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_PyMyLabel_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_PyMyLabel_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_PyMyLabel_QtGui[21].it_td
#define sipClass_QWheelEvent sipImportedTypes_PyMyLabel_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_PyMyLabel_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_PyMyLabel_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_PyMyLabel_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_PyMyLabel_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_PyMyLabel_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_PyMyLabel_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_PyMyLabel_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_PyMyLabel_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_PyMyLabel_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_PyMyLabel_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_PyMyLabel_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_PyMyLabel_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_PyMyLabel_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_PyMyLabel_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_PyMyLabel_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_PyMyLabel_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_PyMyLabel_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_PyMyLabel_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_PyMyLabel_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_PyMyLabel_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_PyMyLabel_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_PyMyLabel_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_PyMyLabel_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_PyMyLabel_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_PyMyLabel_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_PyMyLabel_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_PyMyLabel_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_PyMyLabel_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_PyMyLabel_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_PyMyLabel_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_PyMyLabel_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_PyMyLabel_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_PyMyLabel_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_PyMyLabel_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_PyMyLabel_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_PyMyLabel_QtGui[15].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_PyMyLabel_QtGui[];

#define sipType_QWidget sipImportedTypes_PyMyLabel_QtWidgets[3].it_td
#define sipClass_QWidget sipImportedTypes_PyMyLabel_QtWidgets[3].it_td->u.td_wrapper_type

#define sipType_QFrame sipImportedTypes_PyMyLabel_QtWidgets[0].it_td
#define sipClass_QFrame sipImportedTypes_PyMyLabel_QtWidgets[0].it_td->u.td_wrapper_type

#define sipType_QLabel sipImportedTypes_PyMyLabel_QtWidgets[1].it_td
#define sipClass_QLabel sipImportedTypes_PyMyLabel_QtWidgets[1].it_td->u.td_wrapper_type

#define sipType_QStyleOptionFrame sipImportedTypes_PyMyLabel_QtWidgets[2].it_td
#define sipClass_QStyleOptionFrame sipImportedTypes_PyMyLabel_QtWidgets[2].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_PyMyLabel_QtWidgets[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_PyMyLabel_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_PyMyLabel_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_PyMyLabel_qt_metacast;

#endif
